http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  products:
    host: localhost
    paths: '/api/products'
    methods: ["GET", "POST", "PUT", "DELETE"]
  employee:
    host: localhost
    paths: '/api/employee'
    methods: ["GET", "POST", "PUT", "DELETE"]
  users:
    host: localhost
    paths: '/api/users'
    methods: ["GET", "POST", "PUT", "DELETE"]
serviceEndpoints:
  api:
    url: 'http://localhost:3000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: products
    apiEndpoints:
      - products
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: api 
              changeOrigin: true
  - name: employee
    apiEndpoints:
      - employee
    policies:
      - proxy:
          - action:
              serviceEndpoint: api 
              changeOrigin: true
  - name: users
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: api 
              changeOrigin: true
